app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', ['uses' => 'Admin\IndexController@index', 'as' => 'home', 'middleware' => 'auth']);

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function() {
    Route::controller('login',
        'LoginController',
        [
            'getIndex' => 'admin.login.index',
            'postSignIn' => 'admin.login.sign_in',
            'getSignOut' => 'admin.login.sign_out',
        ]
    );

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/', ['uses' => 'IndexController@index', 'as' => 'admin.home']);
        Route::get('user/list', ['uses' => 'UserController@userList', 'as' => 'admin.user-list']);
        Route::get('user/profile', ['uses' => 'UserController@profile', 'as' => 'admin.user.profile']);
        Route::put('user/update-profile', ['uses' => 'UserController@updateProfile', 'as' => 'admin.user.update.profile']);
        Route::get('ingredient/related/{id}', ['uses' => 'IngredientController@related', 'as' => 'admin.ingredient.related']);

        Route::get('vendor-ingredient-doc/download/{docId}', ['uses' => 'VendorIngredientDocController@download', 'as' => 'admin.vendor_ingredient_doc.download']);
        Route::get('vendor-ingredient-doc/doc-type', ['uses' => 'VendorIngredientDocController@getDocTypes', 'as' => 'admin.vendor_ingredient_doc.doc_type']);
        Route::get('vendor/check-docs/{vendorId}/{ingredientId}', ['uses' => 'VendorController@checkDocs', 'as' => 'admin.vendor.check_docs']);
        Route::get('vendor-quote-doc/download/{docId}', ['uses' => 'VendorQuoteDocController@download', 'as' => 'admin.vendor_quote_doc.download']);
        Route::resource('ingredient', 'IngredientController');
        Route::resource('vendor', 'VendorController');
        Route::resource('vendor-ingredient-doc', 'VendorIngredientDocController');
        Route::resource('vendor-address', 'VendorAddressController');
        Route::resource('vendor-quote', 'VendorQuoteController');
        Route::resource('vendor-quote-doc', 'VendorQuoteDocController');
        Route::resource('vendor-contact', 'ContactController');
    });

    Route::group(['middleware' => 'mustBeAdmin'], function(){
        Route::resource('user', 'UserController');

        //for tools
        Route::get('tools/import-vendors', ['uses' => 'ToolsController@importVendors', 'as' => 'admin.tools.import_vendors']);
    });
});

app/Models/VendorQuote.php
<?php

namespace App\Models;

use App\Consts\TbName;

/**
 * Class VendorQuote
 * @package App\Models
 */
class VendorQuote extends BaseModel
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = TbName::VENDOR_QUOTE_TB;


    /**
     * @var string
     */
    public $primaryKey = 'quote_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'created_id', 'created_date', 'updated_by', 'updated_date', 'ingredient_id', 'vendor_id', 'qty', 'uom', 'unit_price',
        'expire_on', 'contact', 'note', 'quoted_for', 'quote_ref', 'shipfrom', 'qty_max', 'package_type', 'selling_price'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_date', 'updated_date', 'expire_on'
    ];

    /**
     * The storage format of the model's date columns.
     *
     * @var string
     */
    protected $dateFormat = 'Y-m-d';

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function Ingredient()
    {
        return $this->belongsTo(Ingredient::class, 'ingredient_id', 'ingredient_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function QuoteDocs()
    {
        return $this->hasMany(QuoteDoc::class, 'quote_id', 'quote_id');
    }

    /**
     * @param $value
     * @return string
     */
    public function getUnitPriceAttribute($value)
    {
        if($value !== null) {
            return number_format($value, 2);
        }
    }

    /**
     * @param $value
     * @return string
     */
    public function getSellingPriceAttribute($value)
    {
        if($value !== null) {
            return number_format($value, 2);
        }
    }

    /**
     * Vendor Quote filter search
     *
     * @param $query
     * @param $filter
     * @return mixed
     */
    public function scopeSearch($query, $filter)
    {
        if (empty($filter)) {
            return $query;
        }

        foreach($filter as $key => $value) {
            if (empty(trim($value))) {
                continue;
            }
            $value = trim($value);

            if($key=='ingredient_id') {
                $query->where(function($query) use($value){
                    $query->where($this->getTable().'.ingredient_id', '=', $value);
                });
            }
        }

        return $query;
    }
}

app/Http/Controllers/Admin/VendorQuoteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Bll\VendorQuoteBll;
use App\Http\Controllers\BaseController;
use App\Models\Package;
use App\Models\Vendor;
use App\Models\VendorQuote;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\VendorQuoteRequest;
use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Session;

/**
 * Class VendorQuoteController
 * @package App\Http\Controllers\Admin
 */
class VendorQuoteController extends BaseController
{
    /**
     * @var VendorQuote
     */
    protected $vendorQuote;

    /**
     * VendorQuoteController constructor.
     * @param $vendorQuote
     */
    public function __construct(VendorQuote $vendorQuote)
    {
        parent::__construct();
        $this->sidebar('vendors');
        $this->navName('vendor_quote');
        $this->vendorQuote = $vendorQuote;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $vendorId = $request->get('vendor_id');

        if($request->get('filter')) {
            $filter = $request->get('filter');
            Session::put('filter.vendor_quote', $filter);
        }elseif(Session::has('filter.vendor_quote')){
            $filter = Session::get('filter.vendor_quote');
        }else{
            $filter = null;
        }

        $vendorQuotes = VendorQuote::with('ingredient')->search($filter)->where('vendor_id', $vendorId)
            ->paginate(config('view.paginations.admin'));

        $ingredients = Vendor::findOrFail($vendorId)->ingredients()->orderBy('ingredient_name')->lists('ingredient_name', 'ingredients.ingredient_id');

        return view('admin.vendorQuote.quoteList', compact('vendorQuotes', 'vendorId', 'ingredients', 'filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $vendorId = $request->get('vendor_id');
        if(empty($vendorId)) abort(404);

        $ingredientsName = VendorQuoteBll::getIngredientsName($vendorId);
        $quoteFor = VendorQuoteBll::getQuoteFor();
        $packages = VendorQuoteBll::getPackageTypes();

        return view('admin.vendorQuote.quote', compact('ingredientsName', 'vendorId', 'quoteFor', 'packages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  VendorQuoteRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VendorQuoteRequest $request)
    {
        $vendorId = $request->get('vendor_id');

        foreach ($request->only('ingredient_id', 'qty', 'uom', 'unit_price', 'expire_on', 'contact', 'note', 'quoted_for', 'quote_ref',
            'vendor_id', 'shipfrom', 'selling_price', 'qty_max', 'package_type') as $key => $value) {
            $this->vendorQuote->$key = trim($value);
        }
        $this->vendorQuote->created_id = Auth::User()->admin_user_id;
        $this->vendorQuote->created_date = Carbon::now();
        $this->vendorQuote->updated_by = Auth::User()->admin_user_id;
        $this->vendorQuote->updated_date = Carbon::now();

        $result = $this->vendorQuote->save();

        if($result) {
            return redirect()->route('admin.vendor-quote.index', ['vendor_id'=>$vendorId])
                ->with('success',
                    trans('notifications.crud.success.create',
                        [
                            'model' => 'Vendor Quote'
                        ])
                );
        }else{
            return redirect()->route('admin.vendor-quote.create', ['vendor_id'=>$vendorId])
                ->with('fails',
                    trans('notifications.crud.fails.create',
                        [
                            'model' => 'Vendor Quote'
                        ])
                );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $quoteId
     * @return \Illuminate\Http\Response
     */
    public function edit($quoteId)
    {
        $vendorQuote = $this->vendorQuote->findOrFail($quoteId);
        $vendorId = $vendorQuote->vendor_id;
        $ingredientsName = VendorQuoteBll::getIngredientsName($vendorId);
        $quoteFor = VendorQuoteBll::getQuoteFor();
        $packages = VendorQuoteBll::getPackageTypes();

        return view('admin.vendorQuote.quote', compact('vendorId', 'ingredientsName', 'vendorQuote', 'quoteFor', 'packages'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  VendorQuoteRequest  $request
     * @param  int  $quoteId
     * @return \Illuminate\Http\Response
     */
    public function update(VendorQuoteRequest $request, $quoteId)
    {
        $vendorQuote = $this->vendorQuote->findOrFail($quoteId);

        foreach ($request->only('ingredient_id', 'qty', 'uom', 'unit_price', 'expire_on', 'contact', 'note', 'quoted_for',
            'quote_ref', 'vendor_id', 'shipfrom', 'selling_price', 'qty_max', 'package_type') as $key => $value) {
            $vendorQuote->$key = trim($value);
        }
        $vendorQuote->updated_by = Auth::User()->admin_user_id;
        $vendorQuote->updated_date = Carbon::now();

        $result = $vendorQuote->save();

        if($result) {
            return redirect()->route('admin.vendor-quote.index', ['vendor_id'=>$vendorQuote->vendor_id])
                ->with('success',
                    trans('notifications.crud.success.update',
                        [
                            'model' => 'Vendor Quote'
                        ])
                );
        }else{
            return redirect()->route('admin.vendor-quote.edit', $quoteId)
                ->with('fails',
                    trans('notifications.crud.fails.update',
                        [
                            'model' => 'Vendor Quote'
                        ])
                );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $quoteId
     * @return \Illuminate\Http\Response
     */
    public function destroy($quoteId)
    {
        DB::beginTransaction();
        try{
            $vendorQuote = $this->vendorQuote->findOrFail($quoteId);
            $vendorId = $vendorQuote->vendor_id;

            VendorQuoteBll::deleteDocFolderS3($vendorId, $quoteId);
            $this->vendorQuote->findOrFail($quoteId)->delete();
        }catch(\Exception $e){
            Log::error($e->getMessage());
            DB::rollback();
        }
        DB::commit();
    }

}

resources/views/admin/vendorQuote/_quoteForm.blade.php
{{-- vendor ingrendient quote begin --}}
<div class="alert alert-danger hidden">
    <strong>
        <div class="validation-errors"></div>
    </strong>
</div>

@if (Route::currentRouteName() === 'admin.vendor-quote.create')
    <h3 class="header smaller lighter green">Create Vendor Quote</h3>
    {!! Form::open(['route' => 'admin.vendor-quote.store',
        'method' => 'POST',
        'class' => 'form-horizontal',
        'id' => 'create_vendor_quote_form'])
    !!}
@else
    <h3 class="header smaller lighter green">Edit Vendor Quote</h3>
    {!! Form::Model($vendorQuote, ['route' => ['admin.vendor-quote.update', $vendorQuote->quote_id],
        'method' => 'PUT',
        'class' => 'form-horizontal',
        'id' => 'edit_vendor_quote_form'])
     !!}
@endif

<div class="form-group" style="margin-top: 50px;">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Ingredient  Name:
    </label>
    <div class="col-sm-9">
        {!! Form::select('ingredient_id', $ingredientsName, null, ['class'=>'col-xs-8 col-sm-8 chosen', 'placeholder'=>'Select Ingredient Name']) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Quantity:
    </label>
    <div class="col-sm-3">
        {!! Form::text("qty", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
    <label for="form-field-1" class="col-sm-2 control-label ">
        Max Qty:
    </label>
    <div class="col-sm-3">
        {!! Form::text("qty_max", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Unit:
    </label>
    <div class="col-sm-3">
        {!! Form::text("uom", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>

    <label for="form-field-1" class="col-sm-2 control-label ">
        Unit Price:
    </label>
    <div class="col-sm-3">
        {!! Form::text("unit_price", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Package:
    </label>
    <div class="col-sm-3">
        {!! Form::select("package_type", $packages, null, ["class" => "col-xs-10 col-sm-10 chosen"]) !!}
    </div>
    <label for="form-field-1" class="col-sm-2 control-label ">
        Expire On:
    </label>
    <div class="col-sm-3">
        <div class="input-group">
            <input name="expire_on" value="@if(isset($vendorQuote->expire_on)) {{$vendorQuote->expire_on->toDateString()}} @endif"
                   class="form-control date-picker" id="expire_on" type="text" data-date-format="yyyy-mm-dd" />
            <span class="input-group-addon">
                <i class="icon-calendar bigger-110"></i>
            </span>
        </div>
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Contact:
    </label>
    <div class="col-sm-8">
        {!! Form::text("contact", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Note:
    </label>
    <div class="col-sm-8">
        {!! Form::text("note", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Quoted For:
    </label>
    <div class="col-sm-3">
        {!! Form::select('quoted_for', $quoteFor, null, ['class'=>'col-xs-10 col-sm-10']) !!}
    </div>
    <label for="form-field-1" class="col-sm-2 control-label ">
        Quote Ref:
    </label>
    <div class="col-sm-3">
        {!! Form::text("quote_ref", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Ship From:
    </label>
    <div class="col-sm-6">
        {!! Form::text('shipfrom', null, ['class'=>'col-xs-12 col-sm-12']) !!}
    </div>
    <div class="col-sm-2" style="margin-top: 5px;">e.g. zip, city</div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Selling Price:
    </label>
    <div class="col-sm-3">
        {!! Form::text('selling_price', null, ['class'=>'col-xs-12 col-sm-12']) !!}
    </div>
</div>
<div class="space-4"></div>




<div class="space-20"></div>
<input type="hidden" name="vendor_id" id="vendor_id" value="{{$vendorId}}">

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-info" id="vendor_quote_submit_btn" type="submit">
            @if (Route::currentRouteName() === 'admin.vendor-quote.create')
                Submit New Vendor Quote
            @else
                Update Vendor Quote
            @endif
            <i class="icon-ok bigger-110"></i>
        </button>
        <button class="btn btn-warning btn-back" type="button">
            {{ trans('templates.global.back') }}
            <i class="icon-undo bigger-110"></i>
        </button>
    </div>
</div>

{!! Form::close() !!}
{{-- vendor ingrendient quote end --}}

resources/views/admin/vendorQuote/_search.blade.php
<div class="page-header col-sm-12" style="margin-top:19px;">
    {!! Form::open(['route' => ['admin.vendor-quote.index'] ,'method' => 'GET', 'id' => 'vendor_quote_search_form']) !!}
        <div class="col-xs-12" style="padding-left: 0px; margin-top: -25px;">
            @if(!$ingredients->isEmpty())
                {!! Form::select('filter[ingredient_id]', $ingredients, isset($filter['ingredient_id']) ? $filter['ingredient_id'] : '', ['class' => 'search-query pull-left col-xs-5', 'placeholder'=>'Search Ingredient Name']) !!}
            @endif

            <span class="pull-right" style="margin-top: -3px;">
                @if(!$ingredients->isEmpty())
                    <input type="hidden" name="vendor_id" value="{{$vendorId}}">
                    <button type="submit" class="btn btn-purple btn-sm">
                        <i class="icon-search icon-on-right bigger-110"></i>
                        {{ trans('templates.global.search') }}
                    </button>
                @endif
                <a class="btn btn-success btn-sm" href="{{route('admin.vendor-quote.create', ['vendor_id'=>$vendorId])}}">
                    <i class="fa fa-usd" aria-hidden="true"></i>
                    Add Quote
                </a>
            </span>
        </div>
    {!! Form::close() !!}
</div>

resources/views/admin/vendorQuote/quote.blade.php
@extends('layouts.default')
@section('content')
    <div class="col-sm-12 widget-container-span profile-tab">
        @include('partials.errors')
        @include('partials.success')
        @include('partials.fails')

        @include('admin.vendor._nav')

        <div class="widget-box transparent">
            @include('admin.vendorQuote._quoteForm')
        </div>
    </div>
@stop

resources/views/admin/vendorQuote/quoteList.blade.php
@extends('layouts.default')
@section('content')
    <div class="col-sm-12 widget-container-span profile-tab" id="doc_container">
        @include('partials.errors')
        @include('partials.success')
        @include('partials.fails')

        @include('admin.vendor._nav')

        <div class="header green col-sm-12">
            <h3 class="smaller lighter col-sm-9 lead-title">Vendor Quote List</h3>
            <div class="blue col-sm-3 lead-total">Total Quotes: <span>{{$vendorQuotes->total()}}</span></div>
        </div>

        @include('admin.vendorQuote._search')
        <div class="table">
            <table class="table table-striped table-bordered table-hover dataTable" id="sample-table-1">
                <thead>
                <tr>
                    <th class="center">
                        <label>
                            <span class="lbl"></span>
                        </label>
                    </th>
                    <th>Ingredient Name</th>
                    <th>Quantity</th>
                    <th>Unit</th>
                    <th>Unit Price</th>
                    <th>Expire On</th>
                    <th>{{ trans('templates.global.action') }}</th>
                </tr>
                </thead>

                <tbody>
                @if (!$vendorQuotes->isEmpty())
                    @foreach ($vendorQuotes as $key => $quote)
                        @if($quote->ingredient->active)
                            <tr >
                                <td class="center">
                                    <span class="lbl">{{$key+1}}</span>
                                </td>
                                <td>
                                    {{ $quote->ingredient->ingredient_name }}
                                </td>
                                <td>
                                    {{ $quote->qty }}@if(!empty($quote->qty_max)) - {{ $quote->qty_max }} @endif
                                </td>
                                <td>
                                    {{ $quote->uom }}
                                </td>
                                <td>
                                    {{ $quote->unit_price }}
                                </td>
                                <td>
                                    {{ $quote->expire_on->toDateString() }}
                                </td>
                                <td style="width: 150px;">
                                    <div class="btn-group">
                                        <a class="btn btn-xs btn-info" href="{{ route('admin.vendor-quote.edit', $quote) }}">
                                            <i class="icon-edit bigger-120"></i>
                                        </a>
                                        <a class="btn btn-xs btn-danger delete-model" data-url="{{ route('admin.vendor-quote.destroy', $quote) }}">
                                            <i class="icon-trash bigger-120"></i>
                                        </a>
                                        <a class="btn btn-xs btn-success" href="{{ route('admin.vendor-quote-doc.index', ['quote_id'=>$quote]) }}">
                                            <i class="fa fa-file-text-o bigger-120"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endif
                    @endforeach
                @endif
                </tbody>
            </table>
            <div class="row" style="margin-top: 30px;">
                <div class="col-sm-2 text-center">
                </div>
                <div class="col-sm-10">
                    <div class="dataTables_paginate paging_bootstrap">
                        {!! $vendorQuotes->appends(['filter'=>$filter])->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="del_confirm hidden">{{ trans('templates.global.del_confirm') }}</div>
    <div class="del_failed hidden">{{ trans('templates.global.del_failed') }}</div>
    <div class="del_success hidden">{{ trans('templates.global.del_success') }}</div>

@stop