app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', ['uses' => 'Admin\IndexController@index', 'as' => 'home', 'middleware' => 'auth']);

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function() {
    Route::controller('login',
        'LoginController',
        [
            'getIndex' => 'admin.login.index',
            'postSignIn' => 'admin.login.sign_in',
            'getSignOut' => 'admin.login.sign_out',
        ]
    );

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/', ['uses' => 'IndexController@index', 'as' => 'admin.home']);
        Route::get('user/list', ['uses' => 'UserController@userList', 'as' => 'admin.user-list']);
        Route::get('user/profile', ['uses' => 'UserController@profile', 'as' => 'admin.user.profile']);
        Route::put('user/update-profile', ['uses' => 'UserController@updateProfile', 'as' => 'admin.user.update.profile']);
        Route::get('ingredient/related/{id}', ['uses' => 'IngredientController@related', 'as' => 'admin.ingredient.related']);

        Route::get('vendor-ingredient-doc/download/{docId}', ['uses' => 'VendorIngredientDocController@download', 'as' => 'admin.vendor_ingredient_doc.download']);
        Route::get('vendor-ingredient-doc/doc-type', ['uses' => 'VendorIngredientDocController@getDocTypes', 'as' => 'admin.vendor_ingredient_doc.doc_type']);
        Route::get('vendor/check-docs/{vendorId}/{ingredientId}', ['uses' => 'VendorController@checkDocs', 'as' => 'admin.vendor.check_docs']);
        Route::get('vendor-quote-doc/download/{docId}', ['uses' => 'VendorQuoteDocController@download', 'as' => 'admin.vendor_quote_doc.download']);
        Route::resource('ingredient', 'IngredientController');
        Route::resource('vendor', 'VendorController');
        Route::resource('vendor-ingredient-doc', 'VendorIngredientDocController');
        Route::resource('vendor-address', 'VendorAddressController');
        Route::resource('vendor-quote', 'VendorQuoteController');
        Route::resource('vendor-quote-doc', 'VendorQuoteDocController');
        Route::resource('vendor-contact', 'ContactController');
    });

    Route::group(['middleware' => 'mustBeAdmin'], function(){
        Route::resource('user', 'UserController');

        //for tools
        Route::get('tools/import-vendors', ['uses' => 'ToolsController@importVendors', 'as' => 'admin.tools.import_vendors']);
    });
});

resources/views/admin/address/_addressForm.blade.php
{{-- vendor address region begin --}}
<div class="alert alert-danger hidden">
    <strong>
        <div class="validation-errors"></div>
    </strong>
</div>

@if (Route::currentRouteName() === 'admin.vendor-address.create')
    <h3 class="header smaller lighter green">Create Vendor Address</h3>
    {!! Form::open(['route' => 'admin.vendor-address.store',
        'method' => 'POST',
        'class' => 'form-horizontal',
        'id' => 'create_vendor_address_form'])
    !!}
@else
    <h3 class="header smaller lighter green">Edit Vendor Address</h3>
    {!! Form::Model($vendorAddress, ['route' => ['admin.vendor-address.update', $vendorAddress->address_id],
        'method' => 'PUT',
        'class' => 'form-horizontal',
        'id' => 'edit_vendor_address_form'])
     !!}
@endif


<div class="form-group" style="margin-top: 50px;">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Address:
    </label>
    <div class="col-sm-8">
        {!! Form::text("address1", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
    </label>
    <div class="col-sm-8">
        {!! Form::text("address2", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        City:
    </label>
    <div class="col-sm-3">
        {!! Form::text("city", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
    <label for="form-field-1" class="col-sm-2 control-label ">
        State:
    </label>
    <div class="col-sm-3">
        {!! Form::text("state", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Zip:
    </label>
    <div class="col-sm-3">
        {!! Form::text("zip", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
    <label for="form-field-1" class="col-sm-2 control-label ">
        Country:
    </label>
    <div class="col-sm-3">
        {!! Form::text("country", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        First Name:
    </label>
    <div class="col-sm-3">
        {!! Form::text("first_name", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
    <label for="form-field-1" class="col-sm-2 control-label ">
        Last Name:
    </label>
    <div class="col-sm-3">
        {!! Form::text("last_name", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Phone:
    </label>
    <div class="col-sm-3">
        {!! Form::text("phone", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
    <label for="form-field-1" class="col-sm-2 control-label ">
        Email:
    </label>
    <div class="col-sm-3">
        {!! Form::text("email", null, ["class" => "col-xs-10 col-sm-10"]) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Ship Address:
    </label>
    <div class="col-sm-3">
        {!! Form::select('shipfrom_flag', [1=>'YES', 0=>'NO'], null, ['class'=>'col-xs-10 col-sm-10']) !!}
    </div>
    <label for="form-field-1" class="col-sm-2 control-label ">
        Bill Address:
    </label>
    <div class="col-sm-3">
        {!! Form::select('billto_flag', [1=>'YES', 0=>'NO'], null, ['class'=>'col-xs-10 col-sm-10']) !!}
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Default Address:
    </label>
    <div class="col-sm-9">
        {!! Form::select('is_default', [0=>'NO', 1=>'YES'], null, ['class'=>'col-xs-10 col-sm-10']) !!}
    </div>
</div>
<div class="space-4"></div>


<div class="space-20"></div>
<input type="hidden" name="vendor_id" id="vendor_id" value="{{$vendorId}}">

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-info" id="vendor_doc_submit_btn" type="submit">
            @if (Route::currentRouteName() === 'admin.vendor-address.create')
                Save New Vendor Address
            @else
                Update Vendor Address
            @endif
            <i class="icon-ok bigger-110"></i>
        </button>
        <button class="btn btn-warning btn-back" type="button">
            {{ trans('templates.global.back') }}
            <i class="icon-undo bigger-110"></i>
        </button>
    </div>
</div>

{!! Form::close() !!}
{{-- vendor address region end --}}

resources/views/admin/address/_search.blade.php
<div class="page-header col-sm-12" style="margin-top:19px;">
    <div class="col-xs-12" style="padding-left: 0px; margin-top: -25px;">
        <span class="pull-right" style="margin-top: -3px;">
            <a class="btn btn-success btn-sm" href="{{route('admin.vendor-address.create', ['vendor_id'=>$vendorId])}}">
                <i class="fa fa-location-arrow" aria-hidden="true"></i>
                Add Address
            </a>
        </span>
    </div>
</div>

resources/views/admin/address/address.blade.php
@extends('layouts.default')
@section('content')
    <div class="col-sm-12 widget-container-span profile-tab">
        @include('partials.errors')
        @include('partials.success')
        @include('partials.fails')

        @include('admin.vendor._nav')

        <div class="widget-box transparent">
            @include('admin.address._addressForm')
        </div>
    </div>
@stop

resources/views/admin/address/addressList.blade.php
@extends('layouts.default')
@section('content')
    <div class="col-sm-12 widget-container-span profile-tab" id="inv_lead_container">
        @include('partials.errors')
        @include('partials.success')
        @include('partials.fails')

        @include('admin.vendor._nav')

        <div class="header green col-sm-12">
            <h3 class="smaller lighter col-sm-9 lead-title">Vendor Address List</h3>
            <div class="blue col-sm-3 lead-total">Total Records: <span>{{$addresses->count()}}</span></div>
        </div>

        @include('admin.address._search')
        <div class="table">
            <table class="table table-striped table-bordered table-hover dataTable" id="sample-table-1">
                <thead>
                <tr>
                    <th class="center">
                        <label>
                            <span class="lbl"></span>
                        </label>
                    </th>
                    <th id="vendor_cn_title">Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Country</th>
                    <th>Zip</th>
                    <th>Default Address</th>
                    <th>{{ trans('templates.global.action') }}</th>
                </tr>
                </thead>

                <tbody>
                @if (!$addresses->isEmpty())
                    @foreach ($addresses as $key => $address)
                        <tr >
                            <td class="center">
                                <span class="lbl">{{$key+1}}</span>
                            </td>
                            <td>
                                {{ $address->address1 }}
                            </td>
                            <td>
                                {{ $address->city }}
                            </td>
                            <td>
                                {{ $address->state }}
                            </td>
                            <td>
                                {{ $address->country }}
                            </td>
                            <td>
                                {{ $address->zip}}
                            </td>
                            <td>
                                {{ $address->is_default ? 'YES' : 'NO'}}
                            </td>
                            <td style="width: 150px;">
                                <div class="btn-group">
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.vendor-address.edit', $address) }}">
                                        <i class="icon-edit bigger-120"></i>
                                    </a>
                                    @if(!$address->is_default)
                                        <a class="btn btn-xs btn-danger delete-model" data-url="{{route('admin.vendor-address.destroy', $address)}}">
                                            <i class="icon-trash bigger-120"></i>
                                        </a>
                                    @endif
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
    </div>

    <div class="del_confirm hidden">{{ trans('templates.global.del_confirm') }}</div>
    <div class="del_failed hidden">{{ trans('templates.global.del_failed') }}</div>
    <div class="del_success hidden">{{ trans('templates.global.del_success') }}</div>

@stop