app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', ['uses' => 'Admin\IndexController@index', 'as' => 'home', 'middleware' => 'auth']);

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function() {
    Route::controller('login',
        'LoginController',
        [
            'getIndex' => 'admin.login.index',
            'postSignIn' => 'admin.login.sign_in',
            'getSignOut' => 'admin.login.sign_out',
        ]
    );

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/', ['uses' => 'IndexController@index', 'as' => 'admin.home']);
        Route::get('user/list', ['uses' => 'UserController@userList', 'as' => 'admin.user-list']);
        Route::get('user/profile', ['uses' => 'UserController@profile', 'as' => 'admin.user.profile']);
        Route::put('user/update-profile', ['uses' => 'UserController@updateProfile', 'as' => 'admin.user.update.profile']);
        Route::get('ingredient/related/{id}', ['uses' => 'IngredientController@related', 'as' => 'admin.ingredient.related']);

        Route::get('vendor-ingredient-doc/download/{docId}', ['uses' => 'VendorIngredientDocController@download', 'as' => 'admin.vendor_ingredient_doc.download']);
        Route::get('vendor-ingredient-doc/doc-type', ['uses' => 'VendorIngredientDocController@getDocTypes', 'as' => 'admin.vendor_ingredient_doc.doc_type']);
        Route::get('vendor/check-docs/{vendorId}/{ingredientId}', ['uses' => 'VendorController@checkDocs', 'as' => 'admin.vendor.check_docs']);
        Route::get('vendor-quote-doc/download/{docId}', ['uses' => 'VendorQuoteDocController@download', 'as' => 'admin.vendor_quote_doc.download']);
        Route::resource('ingredient', 'IngredientController');
        Route::resource('vendor', 'VendorController');
        Route::resource('vendor-ingredient-doc', 'VendorIngredientDocController');
        Route::resource('vendor-address', 'VendorAddressController');
        Route::resource('vendor-quote', 'VendorQuoteController');
        Route::resource('vendor-quote-doc', 'VendorQuoteDocController');
        Route::resource('vendor-contact', 'ContactController');
    });

    Route::group(['middleware' => 'mustBeAdmin'], function(){
        Route::resource('user', 'UserController');

        //for tools
        Route::get('tools/import-vendors', ['uses' => 'ToolsController@importVendors', 'as' => 'admin.tools.import_vendors']);
    });
});

app/Http/Controllers/Admin/VendorQuoteDocController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Bll\VendorQuoteDocBll;
use App\Http\Controllers\BaseController;
use App\Models\QuoteDoc;
use App\Models\VendorQuote;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\VendorQuoteDocRequest;
use App\Http\Requests;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Class VendorQuoteDocController
 * @package App\Http\Controllers\Admin
 */
class VendorQuoteDocController extends BaseController
{
    /**
     * @var QuoteDoc
     */
    protected $vendorQuoteDoc;

    /**
     * VendorQuoteDocController constructor.
     * @param $vendorQuoteDoc
     */
    public function __construct(QuoteDoc $vendorQuoteDoc)
    {
        parent::__construct();
        $this->sidebar('vendors');
        $this->navName('vendor_quote');
        $this->vendorQuoteDoc = $vendorQuoteDoc;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $quoteId = $request->get('quote_id');
        $vendorQuoteDocs = QuoteDoc::where('quote_id', $quoteId)
            ->paginate(config('view.paginations.admin'));
        $vendorId = VendorQuote::where('quote_id', $quoteId)->pluck('vendor_id');

        return view('admin.vendorQuoteDoc.docList', compact('vendorQuoteDocs', 'vendorId', 'quoteId'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $quoteId = $request->get('quote_id');
        $vendorId = $request->get('vendor_id');
        if(empty($quoteId) || empty($vendorId)) abort(404);

        return view('admin.vendorQuoteDoc.doc', compact('quoteId', 'vendorId'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  VendorQuoteDocRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VendorQuoteDocRequest $request)
    {
        $quoteId = $request->get('quote_id');
        $vendorId = $request->get('vendor_id');

        $file = $request->file('doc');

        $savePath = $vendorId.'/'.$quoteId.'/'.$file->getClientOriginalName();
        $isExist = VendorQuoteDocBll::docIsExistS3($savePath);
        if($isExist) return redirect()->back()->withErrors(['Filename already exists.']);

        $uploadSucc = VendorQuoteDocBll::uploadDocument($file, $vendorId, $quoteId);
        if(!$uploadSucc) {
            return redirect()->route('admin.vendor-quote-doc.create', ['vendor_id'=>$vendorId, 'quote_id'=>$quoteId])
                ->with('fails',
                    trans('notifications.crud.fails.create',
                        [
                            'model' => 'Vendor Ingredient Document'
                        ])
                );
        }else{
            $this->vendorQuoteDoc->file_path = $vendorId.'/'.$quoteId;
            $this->vendorQuoteDoc->doc_name = $file->getClientOriginalName();
        }

        $this->vendorQuoteDoc->quote_id = $quoteId;

        $result = $this->vendorQuoteDoc->save();

        if($result) {
            return redirect()->route('admin.vendor-quote-doc.index', ['quote_id'=>$quoteId])
                ->with('success',
                    trans('notifications.crud.success.create',
                        [
                            'model' => 'Vendor Quote Document'
                        ])
                );
        }else{
            return redirect()->route('admin.vendor-quote-doc.create', ['vendor_id'=>$vendorId, 'quote_id'=>$quoteId])
                ->with('fails',
                    trans('notifications.crud.fails.create',
                        [
                            'model' => 'Vendor Quote Document'
                        ])
                );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $docId
     * @return \Illuminate\Http\Response
     */
    public function destroy($docId)
    {
        DB::beginTransaction();
        try{
            $vendorQuoteDoc = QuoteDoc::with('VendorQuote')->findOrFail($docId);
            $vendorId = $vendorQuoteDoc->VendorQuote->vendor_id;
            $quoteId = $vendorQuoteDoc->quote_id;
            $docName = $vendorQuoteDoc->doc_name;

            VendorQuoteDocBll::deleteDocS3($vendorId, $quoteId, $docName);
            $vendorQuoteDoc->delete();
        }catch(\Exception $e){
            Log::error($e->getMessage());
            DB::rollback();
        }
        DB::commit();
    }

    /**
     * @param $docId
     * @return mixed
     */
    public function download($docId)
    {
        if(empty($docId)) abort(404);
        $vendorQuoteDoc = $this->vendorQuoteDoc->with('VendorQuote')->findOrFail($docId);
        $vendorId = $vendorQuoteDoc->VendorQuote->vendor_id;
        $quoteId = $vendorQuoteDoc->quote_id;
        $docName = $vendorQuoteDoc->doc_name;

        return VendorQuoteDocBll::downloadDocument($vendorId, $quoteId, $docName);
    }
}

resources/views/admin/vendorQuoteDoc/_docForm.blade.php
{{-- vendor quote doc region begin --}}
<div class="alert alert-danger hidden">
    <strong>
        <div class="validation-errors"></div>
    </strong>
</div>

@if (Route::currentRouteName() === 'admin.vendor-quote-doc.create')
    <h3 class="header smaller lighter green">Create Vendor Quote Document</h3>
    {!! Form::open(['route' => 'admin.vendor-quote-doc.store',
        'method' => 'POST',
        'class' => 'form-horizontal',
        'enctype'=>'multipart/form-data',
        'id' => 'create_quote_doc_form'])
    !!}
@else
    <h3 class="header smaller lighter green">Edit Vendor Ingredient Document</h3>
    {!! Form::Model($vendorQuoteDoc, ['route' => ['admin.vendor-quote-doc.update', $vendorQuoteDoc->quote_doc_id],
        'method' => 'PUT',
        'class' => 'form-horizontal',
        'enctype'=>'multipart/form-data',
        'id' => 'edit_quote_doc_form'])
     !!}
@endif

<div class="form-group" style="margin-top: 50px;">
    <label for="form-field-1" class="col-sm-2 control-label ">
        Quote Document:
    </label>
    <div class="col-sm-9">
        {!! Form::file('doc',['multiple'])!!}
    </div>
</div>
<div class="space-20"></div>

<input type="hidden" name="quote_id" id="quote_id" value="{{$quoteId}}">
<input type="hidden" name="vendor_id" id="vendor_id" value="{{$vendorId}}">

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-info" id="vendor_doc_submit_btn" type="submit">
            @if (Route::currentRouteName() === 'admin.vendor-quote-doc.create')
                Upload New Vendor Quote Document
            @else
                Update Vendor Quote Document
            @endif
            <i class="icon-ok bigger-110"></i>
        </button>
        <button class="btn btn-warning btn-back" type="button">
            {{ trans('templates.global.back') }}
            <i class="icon-undo bigger-110"></i>
        </button>
    </div>
</div>

{!! Form::close() !!}
{{-- vendor quote doc end --}}

resources/views/admin/vendorQuoteDoc/_search.blade.php
<div class="page-header col-sm-12" style="margin-top:19px;">
    <div class="col-xs-12" style="padding-left: 0px; margin-top: -25px;">
        <span class="pull-right" style="margin-top: -3px;">
            <a class="btn btn-success btn-sm" href="{{route('admin.vendor-quote-doc.create', ['quote_id'=>$quoteId, 'vendor_id'=>$vendorId])}}">
                <i class="fa fa-file-text-o" aria-hidden="true"></i>
                Add Quote Document
            </a>
            <a class="btn btn-warning btn-sm" href="{{route('admin.vendor-quote.index', ['vendor_id'=>$vendorId])}}">
                <i class="fa fa-usd" aria-hidden="true"></i>
                Back to Quote List
            </a>
        </span>
    </div>
</div>

resources/views/admin/vendorQuoteDoc/doc.blade.php
@extends('layouts.default')
@section('content')
    <div class="col-sm-12 widget-container-span profile-tab">
        @include('partials.errors')
        @include('partials.success')
        @include('partials.fails')

        @include('admin.vendor._nav')

        <div class="widget-box transparent">
            @include('admin.vendorQuoteDoc._docForm')
        </div>
    </div>
@stop

resources/views/admin/vendorQuoteDoc/docList.blade.php
@extends('layouts.default')
@section('content')
    <div class="col-sm-12 widget-container-span profile-tab" id="doc_container">
        @include('partials.errors')
        @include('partials.success')
        @include('partials.fails')

        @include('admin.vendor._nav')

        <div class="header green col-sm-12">
            <h3 class="smaller lighter col-sm-9 lead-title">Vendor Quote Documents List</h3>
            <div class="blue col-sm-3 lead-total">Total Documents: <span>{{$vendorQuoteDocs->total()}}</span></div>
        </div>

        @include('admin.vendorQuoteDoc._search')
        <div class="table">
            <table class="table table-striped table-bordered table-hover dataTable" id="sample-table-1">
                <thead>
                <tr>
                    <th class="center">
                        <label>
                            <span class="lbl"></span>
                        </label>
                    </th>
                    <th>Document Name</th>
                    <th>{{ trans('templates.global.action') }}</th>
                </tr>
                </thead>

                <tbody>
                @if (!$vendorQuoteDocs->isEmpty())
                    @foreach ($vendorQuoteDocs as $key => $doc)
                        <tr >
                            <td class="center">
                                <span class="lbl">{{$key+1}}</span>
                            </td>
                            <td>
                                {{ $doc->doc_name }}
                            </td>
                            <td style="width: 150px;">
                                <div class="btn-group">
                                    @if(\App\Bll\VendorQuoteDocBll::docIsExistS3($vendorId.'/'.$doc->quote_id.'/'.$doc->doc_name))
                                        <a class="btn btn-xs btn-warning" href="{{ route('admin.vendor_quote_doc.download', $doc) }}">
                                            <i class="fa fa-download" aria-hidden="true"></i>
                                        </a>
                                    @endif

                                    <a class="btn btn-xs btn-danger delete-model" data-url="{{ route('admin.vendor-quote-doc.destroy', $doc) }}">
                                        <i class="icon-trash bigger-120"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
    </div>

    <div class="del_confirm hidden">{{ trans('templates.global.del_confirm') }}</div>
    <div class="del_failed hidden">{{ trans('templates.global.del_failed') }}</div>
    <div class="del_success hidden">{{ trans('templates.global.del_success') }}</div>

@stop